sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t amilak/goapp:1.0 .

script:
  - docker run -d -p 8080:8080 amilak/goapp:1.0
  - curl http://localhost:8080
  - docker ps
  - docker exec -it amilak/goapp:1.0 ps -eaf
